version: 2
jobs:
  build:
    working_directory: ~/jTendermint/jabci
    parallelism: 1
    shell: /bin/bash --login
    #environment:
    #  CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    #  CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: maven:3.5.3-jdk-8
    steps:
    - checkout
    #- run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: mvn -B clean
    - run: mvn -B compile
    - run: mvn -B test
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - vendor/bundle
        - ~/virtualenvs
        - ~/.m2
    - store_test_results:
        path: ~/jTendermint/jabci/target/surefire-reports/
  deploy:
    working_directory: ~/jTendermint/jabci
    parallelism: 1
    shell: /bin/bash --login
    #environment:
    #  CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    #  CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: maven:3.5.3-jdk-8
    steps:
    - checkout
    - run: mkdir -p ~/.gnupg
    - run: cp gpg/pubring.gpg ~/.gnupg/pubring.gpg
    - run: openssl aes-256-cbc -d -in gpg/secret -k $SIGN_SECRET >> ~/.gnupg/secring.gpg -md md5
    - run: mvn -B clean install dependency:resolve-plugins dependency:go-offline
    - run: mvn -B -P release -s circleci.settings.xml -DskipTests deploy -Dgpg.passphrase=$GPG_PASSPHRASE
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                filters:
                    branches:
                        only:
                            - master
